---
title: Networking Attacks
description: "How Can we Detect and Prevent Network Attacks?"
date: 2026-10-12
layout: full
toc: true
toc-expand: 3
---

## Exploration

- {{< iconify fa6-solid book-open size=18px >}} Read chapter five [Computer
Systems Security: Planning for Success](https://web.njit.edu/~rt494/security/)

## Activities

- {{< iconify fa6-solid people-line size=18px >}} **Monday and Wednesday**:
Computer Networking
- {{< iconify fa6-solid people-line size=18px >}} **Friday**: Programming skill check or in-person assessment
- {{< iconify fa6-solid diagram-project size=18px >}} **Friday**: Laboratory session
  - Understand design and use of networking protocols
  - Learn how to detect and defend against network attacks
  - Learn how to exploit network protocol vulnerabilities
  - Continued highlighting of the concept of a "security synapse"
  - Instructor presentations that feature:
    - Explanation of a high-level concept networking protocols
    - In-class activity that connects concepts to real-world scenarios
    - Hands-on examples of the operation and behavior of networking protocols
  - No student discussion leaders for this week's material

## Slides

```{=html}
<iframe class="slide-deck" src="../../slides/weekeight/"></iframe>
```

{{< iconify majesticons presentation-play size=18px >}} Full Screen: [Week Eight: Networking Attacks](../../slides/weekeight/)
