# define the project
project:
  type: website
  # use a port that is not commonly used
  # for other projects that I maintain
  # that leverage Quarto
  preview:
    port: 5559
    browser: false
    watch-inputs: true
    navigate: false

# define the output format
website:
  # do not use a title to keep the
  # navbar less cluttered
  title: ""
  search:
    location: navbar
  reader-mode: false
  back-to-top-navigation: true
  page-navigation: true
  favicon: "icons/securitysynapse.png"
  open-graph: true
  site-url: https://www.securitysynapse.org/
  repo-url: https://github.com/SecuritySynapse/www.securitysynapse.org
  # navbar at the top of the page
  navbar:
    # left navbar is the main one for the site
    # The first link returns to the index page
    left:
      - href: index.qmd
        text: Home
      - syllabus/index.qmd
      - schedule/index.qmd
      - slides/index.qmd
      - projects/index.qmd

  # footer at the bottom of the page
  # give reference to GitHub organization
  # and then to the site's main external resources
  page-footer:
    left: '<a href="https://github.com/SecuritySynapse/www.securitysynapse.org/graphs/contributors" aria-label="Security Synapse Maintainers">{{< iconify fa copyright >}} Security Synapse</a>'
    right:
      - text: "{{< iconify fa github size=18px >}}"
        href: https://github.com/SecuritySynapse/
      - text: "{{< iconify fa github-square size=18px >}}"
        href: https://github.com/SecuritySynapse/www.securitysynapse.org/
      - text: "{{< iconify bi discord size=19px >}}"
        href: https://discord.gg/juUXz7d4Jh

# define details about the website
# style, the baseline theme, and then
# the local updates to the theme
format:
  html:
    mainfont: Inter
    monofont: Ubuntu Mono
    fontsize: 1.25em
    theme: zephyr
    highlight-style: github
    css: css/styles.css
    include-in-header:
      # include in the header preconnect and theme-color
      - file: _include/html/header-include.html

# automatically freeze
# the execution of the computations
# to make rendering faster
execute:
  freeze: auto
