---
title: "Security Vulnerabilities"
description: "What Are Best Practices for Handling Vulnerabilities?"
date: "2026-11-16"
layout: full
toc: true
toc-expand: 3
---

## Exploration

- {{< iconify fa6-solid book-open size=18px >}} Read chapters eight and nine in
[Computer Systems Security: Planning for
Success](https://web.njit.edu/~rt494/security/)

## Activities

- {{< iconify fa6-solid people-line size=18px >}} **Monday and Wednesday**:
Security Solutions
- {{< iconify fa6-solid people-line size=18px >}} **Friday**: Programming skill check or in-person assessment
- {{< iconify fa6-solid diagram-project size=18px >}} **Friday**: Laboratory session
  - Explore terms and concepts in security vulnerability management
  - Complete a case study on the topic of secrets in GitHub repositories
  - Learn more about common vulnerabilities and exposures (CVEs)
  - Understand how to use the common vulnerability scoring system (CVSS)
  - Continued highlighting of the concept of a "security synapse"
  - Student presentations that feature:
    - Explanation of a high-level concepts behind security scanning
    - In-class activity that connects concepts to real-world scenarios
    - Hands-on examples of methods for assess security vulnerabilities
    - Demonstrate the use of a practical approach to vulnerabilities

## Slides

```{=html}
<iframe class="slide-deck" src="../../slides/weekthirteen/"></iframe>
```

{{< iconify majesticons presentation-play size=18px >}} Full Screen: [Week
Thirteen: Security Vulnerabilities](../../slides/weekthirteen/)
