---
title: Schedule
layout: full
toc: true
listing:
  - id: featured-weeks
    type: default
    sort-ui: true
    filter-ui: true
    fields: [date,title,description]
    field-display-names:
      description: "Objective"
    contents:
      - "week*/**/*.qmd"
    sort:
      - "date"
      - "title"
      - "description"
---

## Weekly Schedule

:::{#featured-weeks}
:::

## Additional Details

### High-Level Overview

- **Module One** 
  - **Topic**: Basics of Computer Security
  - **Weeks**: One through six
  - **Chapters**: One through three in [CSP](https://web.njit.edu/~rt494/security/) and selected chapters from [CCP](https://inventwithpython.com/cracking)
  - **Midterm Examination One**: Week six during the laboratory session
  - **In-Person Assessment One**: Week six during the classroom sessions

- **Module Two** 
  - **Topic**: Challenges and Solutions in Computer Security
  - **Weeks**: Seven through eleven
  - **Chapters**: Four through six in [CSP](https://web.njit.edu/~rt494/security/) and selected chapters from [CCP](https://inventwithpython.com/cracking)
  - **Midterm Examination Two**: Week eleven during the laboratory session
  - **In-Person Assessment Two**: Week eleven during the classroom sessions

- **Module Three** 
  - **Topic**: Advanced Topics in Computer Security
  - **Weeks**: Twelve through sixteen
  - **Chapters**: Seven through ten in [CSP](https://web.njit.edu/~rt494/security/) and selected chapters from [CCP](https://inventwithpython.com/cracking)
  - **Final Examination**: Week sixteen during the final examination period

### Schedule Details

#### Week-by-Week

- **Date Ranges**
  - **Module One**: Week One through Week Six
  - **Module Two**: Week Seven through Week Eleven
  - **Module Three**: Week Twelve through Week Sixteen
  - **Semester Starts**: Week One, August 26 -- August 30, 2024
  - **Semester Ends**: Week Sixteen, December 9, 2024 -- December 12, 2024
- **Additional Dates**
  - *Examinations*
    - **Midterm Exam One**: Week Six
    - **Midterm Exam Two**: Week Eleven
    - **Final Exam**: Week Sixteen
  - *In-Person Assessments*
    - **In-Person Assessment One**: Week Six
    - **In-Person Assessment Two**: Week Eleven
      - **Note**: Both occur during Tuesday and Thursday class sessions
    - **In-Person Assessment Three**: Week Sixteen
      - **Note**: Occurs during the final examination period
  - *Breaks*  
    - **Labor Day**: Week Two
    - **All-College Programming**: Week Eleven
    - **Fall Break**: Week Eight
    - **Thanksgiving Break**: Week Fourteen

#### Important Dates

- **Midterm Executable Examination One**
    - **Date**: Monday, September 30, 2024
    - **Time**: 2:30 -- 4:30 PM
    - **Location**: Alden 109
- **Midterm Executable Examination Two**
    - **Date**: Monday, November 4, 2024
    - **Time**: 2:30 -- 4:30 PM
    - **Location**: Alden 109
- **Computer Security Summit Presentations**
    - **Date**: Monday, December 5, 2024
    - **Time**: 9:30 AM -- 10:45 AM
    - **Location**: Alden 109
    - **Format**: Three to five minute lightning talks
- **Final Executable Examination**
    - **Examination Code**: C
    - **Date**: Monday, December 9, 2024
    - **Time**: 7:00 PM -- 10:00 PM
    - **Location**: Alden 109
- **Final In-Person Assessment**
    - **Date**: Monday, December 9, 2024
    - **Time**: 7:00 PM -- 10:00 PM
    - **Location**: Alden 109
    - **Task**: Answer technical questions about source code
- **Completed Computer Security Summit Project**
    - **Date**: Thursday, December 12, 2024
    - **Time**: 11:59 PM
    - **Task**: Submit final report through GitHub

::: {.callout-note appearance="minimal" title="Textbook Abbreviations" collapse="false"}

- **CSP**: [Computer Systems Security: Planning for
Success](https://web.njit.edu/~rt494/security/)
- **CCP**: [Cracking Codes with Python](https://inventwithpython.com/cracking/)
- **OSTEP**: [Operating Systems: Three Easy Pieces](https://pages.cs.wisc.edu/~remzi/OSTEP/) 

:::
