---
title: "Access Controls"
description: "How Can We Securely Access Systems and Data?"
date: "2026-11-09"
layout: full
toc: true
toc-expand: 3
---

## Exploration

- {{< iconify fa6-solid book-open size=18px >}} Read chapter seven in [Computer
Systems Security: Planning for Success](https://web.njit.edu/~rt494/security/)
- {{< iconify fa6-solid book-open size=18px >}} Read chapter fifty-five in
[OSTEP](https://pages.cs.wisc.edu/~remzi/OSTEP/)

## Activities

- {{< iconify fa6-solid people-line size=18px >}} **Monday and Wednesday**:
Security Solutions
- {{< iconify fa6-solid people-line size=18px >}} **Friday**: Programming skill check or in-person assessment
- {{< iconify fa6-solid diagram-project size=18px >}} **Friday**: Laboratory session
  - Understand the trade-offs in approaches to access control
  - Develop more insights into multi-factor authentication
  - Explore strategies to authentication and authorization
  - Discover how an operating system plays a critical role in security
  - Continued highlighting of the concept of a "security synapse"
  - Student presentations that feature:
    - Explanation of a high-level concepts behind access control
    - In-class activity that connects concepts to real-world scenarios
    - Hands-on examples of the operation and behavior of access control methods
    - Demonstrate the use of a practical approach to access control

## Slides

```{=html}
<iframe class="slide-deck" src="../../slides/weektwelve/"></iframe>
```

{{< iconify majesticons presentation-play size=18px >}} Full Screen: [Week Twelve: Security Solutions](../../slides/weektwelve/)
